---
- hosts: aws
  become: yes
  tasks:
    - name: Ping the AWS VM
      ping:
    
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Add the user factorio with no home directory
      user:
        name: factorio
        shell: /sbin/nologin
        append: yes
        comment: Factorio service user
        state: present
      become: yes

    # https://docs.ansible.com/ansible/latest/modules/file_module.html
    - name: Create the Factorio directory for the download
      file:
        path: /opt/factorio/
        owner: factorio
        group: root
        state: directory
        mode: '0755'
      become: yes
    
    # https://docs.ansible.com/ansible/latest/modules/get_url_module.html
    - name: Download the Factorio binary file
      get_url:
        url: https://www.factorio.com/get-download/0.17.79/headless/linux64
        dest: /opt/factorio/server_17_79.tar.xz
        mode: '0440'
        owner: factorio
      become: yes
    
    # https://docs.ansible.com/ansible/latest/modules/unarchive_module.html
    - name: Unarchive the Factorio binary
      unarchive:
        src: /opt/factorio/server_17_79.tar.xz
        dest: /opt/
        owner: factorio
        remote_src: yes # Important!!!
      become: yes

    - name: Create the save directory
      file:
        path: /opt/factorio/saves
        owner: factorio
        state: directory
    
    - name: Copy the example server file
      copy:
        src: /opt/factorio/data/server-settings.example.json
        dest: /opt/factorio/data/server-settings.json
        owner: factorio
        remote_src: yes

    # Edit the factorio config file


# Further documentation
# How to Factorio headless: https://gist.github.com/othyn/e1287fd937c1e267cdbcef07227ed48c
# Factorio Init Script: https://github.com/Bisa/factorio-init