---
- hosts: pis
  tasks:
    - name: Create a folder for the application
      file:
        path: /home/pascal/rss_cli/
        state: directory

    - name: Download the source code from github
      git:
        # bare: no
        dest: /home/pascal/rss_cli/
        repo: https://github.com/Warryz/RSS_CLI

    - name: Compile the latest version of the code
      docker_container:
        