---
- hosts: pi
  remote_user: "{{ansible_user}}"

  tasks:
   # Siehe: https://docs.ansible.com/ansible/latest/modules/docker_container_module.html
    
    - name: Start the mumble server container
      docker_container:
        name: mumble-server
        pull: yes
        image: tingvarsson/mumble
        restart_policy: unless-stopped
        restart: yes
        detach: yes
        ports:
          - "64738:64738"
          - "64738:64738/udp"
        volumes:
          - /home/{{ansible_ssh_user}}/docker-mumble/:/config/
        state: started