---
- hosts: pis
  # You may need to add --ask-become-pass -b on the command line
  become: yes
  tasks:
    - name: Allow passwordless sudo for my account
      lineinfile:
        path: /etc/sudoers
        state: present
        line: "pascal ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: Disallow password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
      notify: 
        - Restart ssh

    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
      notify: 
        - Restart ssh
