---
- hosts: pis
  # You may need to add --ask-become-pass -b on the command line
  become: yes
  tasks:
    - lineinfile:
        path: /etc/sudoers
        state: present
        line: 'pascal ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'