---
- hosts: 192.168.2.16
  become: yes
  tasks:
    - name: Ping the Raspi
      ping:
    
    - name: Install pip3 package with apt
      package:
       name: python3-pip
       state: present
    
    - name: Install docker package with pip3
      pip:
        name: docker
        executable: pip3
        
    - name: Pull latest flutter container
      docker_container:
       pull: yes
       name: flutter
       image: cirrusci/flutter
       state: stopped

       #  docker pull cirrusci/flutter