---
- hosts: pi
  tasks:
    - name: Ping the Raspi
      ping:

    # See: https://docs.ansible.com/ansible/latest/modules/apt_module.html#examples
    - name: Run apt update
      apt:
        update_cache: yes
      become: true

    - name: Run apt upgrade
      apt:
        name: "*"
        state: latest
      become: true
